-- ================================================================
-- COMPLETE DATABASE SCHEMA EXPORT
-- Database: company_forum
-- Exported: 2025-11-12T16:09:54.969Z
-- Generated by: export-database-schema.js
-- ================================================================

-- DROP DATABASE IF EXISTS `company_forum`;
-- CREATE DATABASE `company_forum` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE `company_forum`;

SET FOREIGN_KEY_CHECKS = 0;

-- ================================================================
-- TABLES
-- ================================================================

-- Table: announcement_read_receipts
-- Rows: 0, Size: 0.03 MB
-- Foreign Keys: 2
--   announcement_id -> department_announcements(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `announcement_read_receipts`;

CREATE TABLE `announcement_read_receipts` (
  `announcement_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `read_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`announcement_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `announcement_read_receipts_ibfk_1` FOREIGN KEY (`announcement_id`) REFERENCES `department_announcements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `announcement_read_receipts_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: audit_log
-- Rows: 0, Size: 0.08 MB
-- Foreign Keys: 1
--   actor_id -> users(id)

DROP TABLE IF EXISTS `audit_log`;

CREATE TABLE `audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `actor_id` bigint DEFAULT NULL,
  `action` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_id` bigint DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `details` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_actor` (`actor_id`),
  KEY `idx_target` (`target_type`,`target_id`),
  CONSTRAINT `audit_log_ibfk_1` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: bookmarks
-- Rows: 0, Size: 0.06 MB
-- Foreign Keys: 2
--   user_id -> users(id)
--   post_id -> posts(id)

DROP TABLE IF EXISTS `bookmarks`;

CREATE TABLE `bookmarks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `post_id` bigint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_post` (`user_id`,`post_id`),
  KEY `post_id` (`post_id`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `bookmarks_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `bookmarks_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: comment_attachments
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   comment_id -> comments(id)
--   file_id -> files(id)

DROP TABLE IF EXISTS `comment_attachments`;

CREATE TABLE `comment_attachments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `comment_id` bigint NOT NULL,
  `file_id` bigint NOT NULL,
  `sort_order` int DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `file_id` (`file_id`),
  KEY `idx_comment` (`comment_id`),
  CONSTRAINT `comment_attachments_ibfk_1` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comment_attachments_ibfk_2` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: comment_reactions
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 3
--   comment_id -> comments(id)
--   user_id -> users(id)
--   reaction_type_id -> reaction_types(id)

DROP TABLE IF EXISTS `comment_reactions`;

CREATE TABLE `comment_reactions` (
  `comment_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `reaction_type_id` tinyint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`comment_id`,`user_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  CONSTRAINT `comment_reactions_ibfk_1` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comment_reactions_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comment_reactions_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: comments
-- Rows: 11, Size: 0.09 MB
-- Foreign Keys: 4
--   post_id -> posts(id)
--   parent_id -> comments(id)
--   author_id -> users(id)
--   deleted_by -> users(id)

DROP TABLE IF EXISTS `comments`;

CREATE TABLE `comments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `post_id` bigint NOT NULL,
  `author_id` bigint NOT NULL,
  `parent_id` bigint DEFAULT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_html` text COLLATE utf8mb4_unicode_ci,
  `path` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `depth` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` bigint DEFAULT NULL,
  `reaction_count` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_post` (`post_id`),
  KEY `idx_author` (`author_id`),
  KEY `idx_path` (`path`(255)),
  KEY `idx_parent` (`parent_id`),
  KEY `deleted_by` (`deleted_by`),
  CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comments_ibfk_2` FOREIGN KEY (`parent_id`) REFERENCES `comments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comments_ibfk_3` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comments_ibfk_4` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=104 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: conversation_participants
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   conversation_id -> conversations(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `conversation_participants`;

CREATE TABLE `conversation_participants` (
  `conversation_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `joined_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `unread_count` int NOT NULL DEFAULT '0',
  `last_read_message_id` bigint DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`conversation_id`,`user_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_unread` (`user_id`,`unread_count`),
  CONSTRAINT `conversation_participants_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `conversation_participants_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: conversations
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 1
--   created_by -> users(id)

DROP TABLE IF EXISTS `conversations`;

CREATE TABLE `conversations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `type` enum('dm','group') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'dm',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_message_at` datetime DEFAULT NULL,
  `avatar_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_last_message` (`last_message_at`),
  CONSTRAINT `conversations_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: department_announcements
-- Rows: 0, Size: 0.06 MB
-- Foreign Keys: 2
--   department_id -> departments(id)
--   author_id -> users(id)

DROP TABLE IF EXISTS `department_announcements`;

CREATE TABLE `department_announcements` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `department_id` bigint NOT NULL,
  `author_id` bigint NOT NULL,
  `title` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_html` text COLLATE utf8mb4_unicode_ci,
  `priority` enum('low','normal','high','urgent') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  `published_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `is_pinned` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `author_id` (`author_id`),
  KEY `idx_dept_published` (`department_id`,`published_at`),
  KEY `idx_priority` (`priority`),
  CONSTRAINT `department_announcements_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `department_announcements_ibfk_2` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: departments
-- Rows: 56, Size: 0.09 MB
-- Foreign Keys: 2
--   parent_id -> departments(id)
--   manager_id -> users(id)

DROP TABLE IF EXISTS `departments`;

CREATE TABLE `departments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `manager_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `idx_name` (`name`),
  KEY `idx_code` (`code`),
  KEY `parent_id` (`parent_id`),
  KEY `manager_id` (`manager_id`),
  CONSTRAINT `departments_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `departments_ibfk_2` FOREIGN KEY (`manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: employee_records
-- Rows: 5, Size: 0.09 MB
-- Foreign Keys: 3
--   user_id -> users(id)
--   department_id -> departments(id)
--   team_id -> teams(id)

DROP TABLE IF EXISTS `employee_records`;

CREATE TABLE `employee_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `department_id` bigint DEFAULT NULL,
  `team_id` bigint DEFAULT NULL,
  `position` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employee_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `contract` json DEFAULT NULL,
  `work_history` json DEFAULT NULL,
  `status` enum('active','on_hold','resigned') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `employee_code` (`employee_code`),
  KEY `department_id` (`department_id`),
  KEY `team_id` (`team_id`),
  KEY `idx_user_status` (`user_id`,`status`),
  KEY `idx_employee_code` (`employee_code`),
  CONSTRAINT `employee_records_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `employee_records_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `employee_records_ibfk_3` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: event_attendees
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   event_id -> events(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `event_attendees`;

CREATE TABLE `event_attendees` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `event_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `status` enum('going','maybe','not_going') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'going',
  `joined_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_event_user` (`event_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `event_attendees_ibfk_1` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `event_attendees_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: event_departments
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   event_id -> events(id)
--   department_id -> departments(id)

DROP TABLE IF EXISTS `event_departments`;

CREATE TABLE `event_departments` (
  `event_id` bigint NOT NULL,
  `department_id` bigint NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`event_id`,`department_id`),
  KEY `idx_event_id` (`event_id`),
  KEY `idx_department_id` (`department_id`),
  CONSTRAINT `event_departments_ibfk_1` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `event_departments_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: events
-- Rows: 78, Size: 0.06 MB
-- Foreign Keys: 2
--   created_by -> users(id)
--   department_id -> departments(id)

DROP TABLE IF EXISTS `events`;

CREATE TABLE `events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime NOT NULL,
  `created_by` bigint NOT NULL,
  `department_id` bigint DEFAULT NULL,
  `max_attendees` int DEFAULT NULL,
  `is_public` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_events_department` (`department_id`),
  CONSTRAINT `events_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_events_department` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=80 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: files
-- Rows: 15, Size: 0.05 MB
-- Foreign Keys: 1
--   uploader_id -> users(id)

DROP TABLE IF EXISTS `files`;

CREATE TABLE `files` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `uploader_id` bigint DEFAULT NULL,
  `storage_path` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `original_name` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mime_type` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `size_bytes` bigint NOT NULL,
  `max_size_mb` int NOT NULL DEFAULT '50',
  `checksum` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_private` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_uploader` (`uploader_id`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `files_ibfk_1` FOREIGN KEY (`uploader_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: hashtags
-- Rows: 0, Size: 0.06 MB

DROP TABLE IF EXISTS `hashtags`;

CREATE TABLE `hashtags` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tag` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `usage_count` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tag` (`tag`),
  KEY `idx_tag` (`tag`),
  KEY `idx_usage_count` (`usage_count`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: meeting_attachments
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   meeting_id -> meetings(id)
--   file_id -> files(id)

DROP TABLE IF EXISTS `meeting_attachments`;

CREATE TABLE `meeting_attachments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `meeting_id` bigint NOT NULL,
  `file_id` bigint NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `file_id` (`file_id`),
  KEY `idx_meeting` (`meeting_id`),
  CONSTRAINT `meeting_attachments_ibfk_1` FOREIGN KEY (`meeting_id`) REFERENCES `meetings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `meeting_attachments_ibfk_2` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: meeting_attendees
-- Rows: 3, Size: 0.03 MB
-- Foreign Keys: 2
--   meeting_id -> meetings(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `meeting_attendees`;

CREATE TABLE `meeting_attendees` (
  `meeting_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `status` enum('invited','accepted','declined','tentative') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'invited',
  `notified` tinyint(1) NOT NULL DEFAULT '0',
  `reminder_sent` tinyint(1) NOT NULL DEFAULT '0',
  `responded_at` datetime DEFAULT NULL,
  PRIMARY KEY (`meeting_id`,`user_id`),
  KEY `idx_user_status` (`user_id`,`status`),
  CONSTRAINT `meeting_attendees_ibfk_1` FOREIGN KEY (`meeting_id`) REFERENCES `meetings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `meeting_attendees_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: meeting_departments
-- Rows: 5, Size: 0.05 MB
-- Foreign Keys: 2
--   meeting_id -> meetings(id)
--   department_id -> departments(id)

DROP TABLE IF EXISTS `meeting_departments`;

CREATE TABLE `meeting_departments` (
  `meeting_id` bigint NOT NULL,
  `department_id` bigint NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`meeting_id`,`department_id`),
  KEY `idx_meeting_id` (`meeting_id`),
  KEY `idx_department_id` (`department_id`),
  CONSTRAINT `meeting_departments_ibfk_1` FOREIGN KEY (`meeting_id`) REFERENCES `meetings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `meeting_departments_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: meeting_participants
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   meeting_id -> meetings(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `meeting_participants`;

CREATE TABLE `meeting_participants` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `meeting_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `status` enum('invited','accepted','declined','maybe') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'invited',
  `joined_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_meeting_user` (`meeting_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `meeting_participants_ibfk_1` FOREIGN KEY (`meeting_id`) REFERENCES `meetings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `meeting_participants_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: meetings
-- Rows: 75, Size: 0.06 MB
-- Foreign Keys: 2
--   organizer_id -> users(id)
--   department_id -> departments(id)

DROP TABLE IF EXISTS `meetings`;

CREATE TABLE `meetings` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `organizer_id` bigint DEFAULT NULL,
  `department_id` bigint DEFAULT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime DEFAULT NULL,
  `location` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meeting_link` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `recurrence` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `is_cancelled` tinyint(1) NOT NULL DEFAULT '0',
  `cancelled_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `department_id` (`department_id`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_organizer` (`organizer_id`),
  CONSTRAINT `meetings_ibfk_1` FOREIGN KEY (`organizer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `meetings_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=77 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: message_attachments
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   message_id -> messages(id)
--   file_id -> files(id)

DROP TABLE IF EXISTS `message_attachments`;

CREATE TABLE `message_attachments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `message_id` bigint NOT NULL,
  `file_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `file_id` (`file_id`),
  KEY `idx_message` (`message_id`),
  CONSTRAINT `message_attachments_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `message_attachments_ibfk_2` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: message_read_receipts
-- Rows: 0, Size: 0.03 MB
-- Foreign Keys: 2
--   message_id -> messages(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `message_read_receipts`;

CREATE TABLE `message_read_receipts` (
  `message_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `read_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_id`,`user_id`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `message_read_receipts_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `message_read_receipts_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: messages
-- Rows: 0, Size: 0.09 MB
-- Foreign Keys: 2
--   conversation_id -> conversations(id)
--   sender_id -> users(id)

DROP TABLE IF EXISTS `messages`;

CREATE TABLE `messages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `conversation_id` bigint NOT NULL,
  `sender_id` bigint DEFAULT NULL,
  `content` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` datetime DEFAULT NULL,
  `edited` tinyint(1) NOT NULL DEFAULT '0',
  `edited_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sender_id` (`sender_id`),
  KEY `idx_conversation` (`conversation_id`),
  KEY `idx_created_at` (`created_at`),
  FULLTEXT KEY `ft_message_content` (`content`),
  CONSTRAINT `messages_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `messages_ibfk_2` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: monthly_activity_summary
-- Rows: 0, Size: 0.06 MB
-- Foreign Keys: 1
--   dept_id -> departments(id)

DROP TABLE IF EXISTS `monthly_activity_summary`;

CREATE TABLE `monthly_activity_summary` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `year` int NOT NULL,
  `month` int NOT NULL,
  `dept_id` bigint DEFAULT NULL,
  `posts_count` int NOT NULL DEFAULT '0',
  `comments_count` int NOT NULL DEFAULT '0',
  `active_users_count` int NOT NULL DEFAULT '0',
  `total_reactions` int NOT NULL DEFAULT '0',
  `total_shares` int NOT NULL DEFAULT '0',
  `total_meetings` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_year_month_dept` (`year`,`month`,`dept_id`),
  KEY `dept_id` (`dept_id`),
  KEY `idx_year_month` (`year`,`month`),
  CONSTRAINT `monthly_activity_summary_ibfk_1` FOREIGN KEY (`dept_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: notification_preferences
-- Rows: 0, Size: 0.02 MB
-- Foreign Keys: 1
--   user_id -> users(id)

DROP TABLE IF EXISTS `notification_preferences`;

CREATE TABLE `notification_preferences` (
  `user_id` bigint NOT NULL,
  `notification_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `email_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `push_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`user_id`,`notification_type`),
  CONSTRAINT `notification_preferences_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: notifications
-- Rows: 0, Size: 0.08 MB
-- Foreign Keys: 2
--   user_id -> users(id)
--   actor_id -> users(id)

DROP TABLE IF EXISTS `notifications`;

CREATE TABLE `notifications` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `actor_id` bigint DEFAULT NULL,
  `type` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reference_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reference_id` bigint DEFAULT NULL,
  `payload` json DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT '0',
  `read_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `actor_id` (`actor_id`),
  KEY `idx_user_read` (`user_id`,`is_read`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_type` (`type`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `notifications_ibfk_2` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: permissions
-- Rows: 41, Size: 0.03 MB

DROP TABLE IF EXISTS `permissions`;

CREATE TABLE `permissions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: poll_options
-- Rows: 138, Size: 0.03 MB
-- Foreign Keys: 1
--   poll_id -> polls(id)

DROP TABLE IF EXISTS `poll_options`;

CREATE TABLE `poll_options` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `poll_id` bigint NOT NULL,
  `option_text` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `option_order` int NOT NULL DEFAULT '0',
  `votes_count` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_poll` (`poll_id`),
  CONSTRAINT `poll_options_ibfk_1` FOREIGN KEY (`poll_id`) REFERENCES `polls` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: poll_votes
-- Rows: 0, Size: 0.06 MB
-- Foreign Keys: 3
--   poll_id -> polls(id)
--   option_id -> poll_options(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `poll_votes`;

CREATE TABLE `poll_votes` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `poll_id` bigint NOT NULL,
  `option_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `voted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_poll_user` (`poll_id`,`user_id`,`option_id`),
  KEY `option_id` (`option_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `poll_votes_ibfk_1` FOREIGN KEY (`poll_id`) REFERENCES `polls` (`id`) ON DELETE CASCADE,
  CONSTRAINT `poll_votes_ibfk_2` FOREIGN KEY (`option_id`) REFERENCES `poll_options` (`id`) ON DELETE CASCADE,
  CONSTRAINT `poll_votes_ibfk_3` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: polls
-- Rows: 76, Size: 0.03 MB
-- Foreign Keys: 1
--   created_by -> users(id)

DROP TABLE IF EXISTS `polls`;

CREATE TABLE `polls` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `question` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_by` bigint NOT NULL,
  `allow_multiple` tinyint(1) NOT NULL DEFAULT '0',
  `closes_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_created_by` (`created_by`),
  CONSTRAINT `polls_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=78 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: post_attachments
-- Rows: 14, Size: 0.05 MB
-- Foreign Keys: 2
--   post_id -> posts(id)
--   file_id -> files(id)

DROP TABLE IF EXISTS `post_attachments`;

CREATE TABLE `post_attachments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `post_id` bigint NOT NULL,
  `file_id` bigint NOT NULL,
  `attachment_type` enum('image','video','document','other') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'other',
  `sort_order` int NOT NULL DEFAULT '0',
  `meta` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `file_id` (`file_id`),
  KEY `idx_post` (`post_id`),
  CONSTRAINT `post_attachments_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_attachments_ibfk_2` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: post_categories
-- Rows: 7, Size: 0.03 MB

DROP TABLE IF EXISTS `post_categories`;

CREATE TABLE `post_categories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icon` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `color` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: post_hashtags
-- Rows: 0, Size: 0.03 MB
-- Foreign Keys: 2
--   post_id -> posts(id)
--   hashtag_id -> hashtags(id)

DROP TABLE IF EXISTS `post_hashtags`;

CREATE TABLE `post_hashtags` (
  `post_id` bigint NOT NULL,
  `hashtag_id` bigint NOT NULL,
  PRIMARY KEY (`post_id`,`hashtag_id`),
  KEY `hashtag_id` (`hashtag_id`),
  CONSTRAINT `post_hashtags_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_hashtags_ibfk_2` FOREIGN KEY (`hashtag_id`) REFERENCES `hashtags` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: post_mentions
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   post_id -> posts(id)
--   mentioned_user_id -> users(id)

DROP TABLE IF EXISTS `post_mentions`;

CREATE TABLE `post_mentions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `post_id` bigint NOT NULL,
  `mentioned_user_id` bigint NOT NULL,
  `position` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `post_id` (`post_id`),
  KEY `idx_mentioned_user` (`mentioned_user_id`),
  CONSTRAINT `post_mentions_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_mentions_ibfk_2` FOREIGN KEY (`mentioned_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: post_reactions
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 3
--   post_id -> posts(id)
--   user_id -> users(id)
--   reaction_type_id -> reaction_types(id)

DROP TABLE IF EXISTS `post_reactions`;

CREATE TABLE `post_reactions` (
  `post_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `reaction_type_id` tinyint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`post_id`,`user_id`),
  KEY `user_id` (`user_id`),
  KEY `idx_reaction_type` (`reaction_type_id`),
  CONSTRAINT `post_reactions_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_reactions_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_reactions_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_types` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: post_shares
-- Rows: 0, Size: 0.09 MB
-- Foreign Keys: 4
--   post_id -> posts(id)
--   shared_by -> users(id)
--   department_id -> departments(id)
--   team_id -> teams(id)

DROP TABLE IF EXISTS `post_shares`;

CREATE TABLE `post_shares` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `post_id` bigint NOT NULL,
  `shared_by` bigint NOT NULL,
  `comment` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `visibility` enum('company','department','team','private') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `department_id` bigint DEFAULT NULL,
  `team_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `post_id` (`post_id`),
  KEY `department_id` (`department_id`),
  KEY `team_id` (`team_id`),
  KEY `idx_shared_by` (`shared_by`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `post_shares_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_shares_ibfk_2` FOREIGN KEY (`shared_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_shares_ibfk_3` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `post_shares_ibfk_4` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: post_views
-- Rows: 86, Size: 0.06 MB
-- Foreign Keys: 2
--   post_id -> posts(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `post_views`;

CREATE TABLE `post_views` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `post_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `viewed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `view_duration` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `idx_post_user` (`post_id`,`user_id`),
  KEY `idx_viewed_at` (`viewed_at`),
  CONSTRAINT `post_views_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_views_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: posts
-- Rows: 15, Size: 0.17 MB
-- Foreign Keys: 7
--   author_id -> users(id)
--   department_id -> departments(id)
--   team_id -> teams(id)
--   allowed_group_id -> teams(id)
--   category_id -> post_categories(id)
--   deleted_by -> users(id)
--   pinned_by -> users(id)

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `author_id` bigint NOT NULL,
  `department_id` bigint DEFAULT NULL,
  `team_id` bigint DEFAULT NULL,
  `category_id` int DEFAULT NULL,
  `title` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_html` mediumtext COLLATE utf8mb4_unicode_ci,
  `visibility` enum('company','department','team','private') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'company',
  `allowed_group_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `edited` tinyint(1) NOT NULL DEFAULT '0',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` bigint DEFAULT NULL,
  `reply_count` int NOT NULL DEFAULT '0',
  `reaction_count` int NOT NULL DEFAULT '0',
  `view_count` int NOT NULL DEFAULT '0',
  `share_count` int NOT NULL DEFAULT '0',
  `pinned` tinyint(1) NOT NULL DEFAULT '0',
  `pinned_until` datetime DEFAULT NULL,
  `pinned_by` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_author` (`author_id`),
  KEY `idx_department` (`department_id`),
  KEY `idx_team` (`team_id`),
  KEY `idx_visibility` (`visibility`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_category` (`category_id`),
  KEY `allowed_group_id` (`allowed_group_id`),
  KEY `deleted_by` (`deleted_by`),
  KEY `pinned_by` (`pinned_by`),
  FULLTEXT KEY `ft_posts_content` (`title`,`content`),
  CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `posts_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `posts_ibfk_3` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON DELETE SET NULL,
  CONSTRAINT `posts_ibfk_4` FOREIGN KEY (`allowed_group_id`) REFERENCES `teams` (`id`) ON DELETE SET NULL,
  CONSTRAINT `posts_ibfk_5` FOREIGN KEY (`category_id`) REFERENCES `post_categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `posts_ibfk_6` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `posts_ibfk_7` FOREIGN KEY (`pinned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=115 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: profiles
-- Rows: 109, Size: 0.06 MB
-- Foreign Keys: 1
--   user_id -> users(id)

DROP TABLE IF EXISTS `profiles`;

CREATE TABLE `profiles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `full_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `avatar_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bio` text COLLATE utf8mb4_unicode_ci,
  `phone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `gender` enum('male','female','other','unspecified') COLLATE utf8mb4_unicode_ci DEFAULT 'unspecified',
  `marital_status` enum('single','married','divorced','widowed','unspecified') COLLATE utf8mb4_unicode_ci DEFAULT 'unspecified',
  `address` text COLLATE utf8mb4_unicode_ci COMMENT 'Địa chỉ người dùng',
  `work_info` json DEFAULT NULL,
  `education` json DEFAULT NULL,
  `extras` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_full_name` (`full_name`),
  CONSTRAINT `profiles_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=145 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_activity_logs
-- Rows: 13, Size: 0.06 MB
-- Foreign Keys: 2
--   project_id -> projects(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `project_activity_logs`;

CREATE TABLE `project_activity_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `user_id` bigint DEFAULT NULL,
  `action` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entity_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'project, task, member, file, etc',
  `entity_id` bigint DEFAULT NULL,
  `old_value` text COLLATE utf8mb4_unicode_ci,
  `new_value` text COLLATE utf8mb4_unicode_ci,
  `description` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `idx_project` (`project_id`),
  KEY `idx_created` (`created_at`),
  CONSTRAINT `project_activity_logs_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_activity_logs_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_comments
-- Rows: 9, Size: 0.06 MB
-- Foreign Keys: 3
--   project_id -> projects(id)
--   user_id -> users(id)
--   parent_id -> project_comments(id)

DROP TABLE IF EXISTS `project_comments`;

CREATE TABLE `project_comments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `comment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent_id` bigint DEFAULT NULL COMMENT 'For replies',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`),
  KEY `idx_project` (`project_id`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `project_comments_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_comments_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_comments_ibfk_3` FOREIGN KEY (`parent_id`) REFERENCES `project_comments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_department_tasks
-- Rows: 16, Size: 0.14 MB
-- Foreign Keys: 6
--   project_id -> projects(id)
--   department_id -> departments(id)
--   assigned_by -> users(id)
--   accepted_by -> users(id)
--   submitted_by -> users(id)
--   approved_by -> users(id)

DROP TABLE IF EXISTS `project_department_tasks`;

CREATE TABLE `project_department_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `department_id` bigint NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `assigned_by` bigint NOT NULL COMMENT 'Admin who assigned',
  `priority` enum('low','medium','high','urgent') COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `status` enum('assigned','in_progress','submitted','approved','rejected','completed') COLLATE utf8mb4_unicode_ci DEFAULT 'assigned',
  `deadline` date DEFAULT NULL,
  `estimated_hours` decimal(10,2) DEFAULT '0.00',
  `actual_hours` decimal(10,2) DEFAULT '0.00',
  `progress` tinyint unsigned DEFAULT '0' COMMENT '0-100%',
  `accepted_at` datetime DEFAULT NULL,
  `accepted_by` bigint DEFAULT NULL COMMENT 'Manager who accepted',
  `rejection_reason` text COLLATE utf8mb4_unicode_ci,
  `submitted_at` datetime DEFAULT NULL,
  `submitted_by` bigint DEFAULT NULL,
  `submission_notes` text COLLATE utf8mb4_unicode_ci,
  `approved_at` datetime DEFAULT NULL,
  `approved_by` bigint DEFAULT NULL COMMENT 'Admin who approved',
  `approval_notes` text COLLATE utf8mb4_unicode_ci,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `department_id` (`department_id`),
  KEY `accepted_by` (`accepted_by`),
  KEY `submitted_by` (`submitted_by`),
  KEY `approved_by` (`approved_by`),
  KEY `idx_project_dept` (`project_id`,`department_id`),
  KEY `idx_status` (`status`),
  KEY `idx_deadline` (`deadline`),
  KEY `idx_assigned_by` (`assigned_by`),
  CONSTRAINT `project_department_tasks_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_department_tasks_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_department_tasks_ibfk_3` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`),
  CONSTRAINT `project_department_tasks_ibfk_4` FOREIGN KEY (`accepted_by`) REFERENCES `users` (`id`),
  CONSTRAINT `project_department_tasks_ibfk_5` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`id`),
  CONSTRAINT `project_department_tasks_ibfk_6` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_departments
-- Rows: 39, Size: 0.08 MB
-- Foreign Keys: 4
--   project_id -> projects(id)
--   department_id -> departments(id)
--   assigned_team_id -> teams(id)
--   assigned_by -> users(id)

DROP TABLE IF EXISTS `project_departments`;

CREATE TABLE `project_departments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `department_id` bigint NOT NULL,
  `status` enum('pending','accepted','rejected') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `assigned_team_id` bigint DEFAULT NULL,
  `assigned_by` bigint DEFAULT NULL,
  `assigned_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_project_department` (`project_id`,`department_id`),
  KEY `department_id` (`department_id`),
  KEY `assigned_team_id` (`assigned_team_id`),
  KEY `assigned_by` (`assigned_by`),
  CONSTRAINT `project_departments_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_departments_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_departments_ibfk_3` FOREIGN KEY (`assigned_team_id`) REFERENCES `teams` (`id`) ON DELETE SET NULL,
  CONSTRAINT `project_departments_ibfk_4` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_files
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   project_id -> projects(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `project_files`;

CREATE TABLE `project_files` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_size` bigint DEFAULT NULL COMMENT 'Size in bytes',
  `file_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `idx_project` (`project_id`),
  CONSTRAINT `project_files_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_files_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_member_tasks
-- Rows: 7, Size: 0.11 MB
-- Foreign Keys: 4
--   department_task_id -> project_department_tasks(id)
--   user_id -> users(id)
--   assigned_by -> users(id)
--   approved_by -> users(id)

DROP TABLE IF EXISTS `project_member_tasks`;

CREATE TABLE `project_member_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `department_task_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `assigned_by` bigint NOT NULL COMMENT 'Manager who assigned',
  `priority` enum('low','medium','high','urgent') COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `status` enum('assigned','in_progress','submitted','approved','completed') COLLATE utf8mb4_unicode_ci DEFAULT 'assigned',
  `deadline` date DEFAULT NULL,
  `estimated_hours` decimal(10,2) DEFAULT '0.00',
  `actual_hours` decimal(10,2) DEFAULT '0.00',
  `progress` tinyint unsigned DEFAULT '0' COMMENT '0-100%',
  `started_at` datetime DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `submission_notes` text COLLATE utf8mb4_unicode_ci,
  `approved_at` datetime DEFAULT NULL,
  `approved_by` bigint DEFAULT NULL COMMENT 'Manager who approved',
  `approval_notes` text COLLATE utf8mb4_unicode_ci,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `assigned_by` (`assigned_by`),
  KEY `approved_by` (`approved_by`),
  KEY `idx_dept_task` (`department_task_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_deadline` (`deadline`),
  CONSTRAINT `project_member_tasks_ibfk_1` FOREIGN KEY (`department_task_id`) REFERENCES `project_department_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_member_tasks_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_member_tasks_ibfk_3` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`),
  CONSTRAINT `project_member_tasks_ibfk_4` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_members
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   project_id -> projects(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `project_members`;

CREATE TABLE `project_members` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `role` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('active','inactive','left') COLLATE utf8mb4_unicode_ci DEFAULT 'active',
  `contribution_hours` decimal(10,2) DEFAULT '0.00' COMMENT 'Hours contributed',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `joined_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_project_user` (`project_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `project_members_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_members_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_milestones
-- Rows: 2, Size: 0.03 MB
-- Foreign Keys: 1
--   project_id -> projects(id)

DROP TABLE IF EXISTS `project_milestones`;

CREATE TABLE `project_milestones` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `due_date` date NOT NULL,
  `status` enum('pending','completed','missed') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `completed_at` datetime DEFAULT NULL,
  `order_index` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_project` (`project_id`),
  CONSTRAINT `project_milestones_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_notifications
-- Rows: 1, Size: 0.08 MB
-- Foreign Keys: 3
--   project_id -> projects(id)
--   department_id -> departments(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `project_notifications`;

CREATE TABLE `project_notifications` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `department_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `type` enum('project_assigned','team_assigned','member_added','project_updated') COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_read` tinyint(1) DEFAULT '0',
  `read_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `project_id` (`project_id`),
  KEY `department_id` (`department_id`),
  KEY `idx_user_unread` (`user_id`,`is_read`),
  KEY `idx_created` (`created_at` DESC),
  CONSTRAINT `project_notifications_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_notifications_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_notifications_ibfk_3` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_task_reminders
-- Rows: 0, Size: 0.11 MB
-- Foreign Keys: 3
--   department_task_id -> project_department_tasks(id)
--   member_task_id -> project_member_tasks(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `project_task_reminders`;

CREATE TABLE `project_task_reminders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `department_task_id` bigint DEFAULT NULL,
  `member_task_id` bigint DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `reminder_type` enum('deadline_approaching','overdue','status_update','approval_needed') COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `remind_at` datetime NOT NULL,
  `sent_at` datetime DEFAULT NULL,
  `is_read` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `department_task_id` (`department_task_id`),
  KEY `member_task_id` (`member_task_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_remind_at` (`remind_at`),
  KEY `idx_sent` (`sent_at`),
  KEY `idx_unread` (`user_id`,`is_read`),
  CONSTRAINT `project_task_reminders_ibfk_1` FOREIGN KEY (`department_task_id`) REFERENCES `project_department_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_task_reminders_ibfk_2` FOREIGN KEY (`member_task_id`) REFERENCES `project_member_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_task_reminders_ibfk_3` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_task_reports
-- Rows: 10, Size: 0.11 MB
-- Foreign Keys: 4
--   project_id -> projects(id)
--   department_task_id -> project_department_tasks(id)
--   member_task_id -> project_member_tasks(id)
--   reported_by -> users(id)

DROP TABLE IF EXISTS `project_task_reports`;

CREATE TABLE `project_task_reports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `department_task_id` bigint DEFAULT NULL,
  `member_task_id` bigint DEFAULT NULL,
  `reported_by` bigint NOT NULL,
  `report_type` enum('daily','weekly','monthly','completion','issue') COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `progress` tinyint unsigned DEFAULT NULL COMMENT '0-100%',
  `issues` text COLLATE utf8mb4_unicode_ci COMMENT 'Problems encountered',
  `attachments` json DEFAULT NULL COMMENT 'File paths or URLs',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `reported_by` (`reported_by`),
  KEY `idx_project` (`project_id`),
  KEY `idx_dept_task` (`department_task_id`),
  KEY `idx_member_task` (`member_task_id`),
  KEY `idx_report_type` (`report_type`),
  KEY `idx_created` (`created_at`),
  CONSTRAINT `project_task_reports_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_task_reports_ibfk_2` FOREIGN KEY (`department_task_id`) REFERENCES `project_department_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_task_reports_ibfk_3` FOREIGN KEY (`member_task_id`) REFERENCES `project_member_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_task_reports_ibfk_4` FOREIGN KEY (`reported_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_tasks
-- Rows: 8, Size: 0.09 MB
-- Foreign Keys: 4
--   project_id -> projects(id)
--   assigned_to -> users(id)
--   parent_task_id -> project_tasks(id)
--   created_by -> users(id)

DROP TABLE IF EXISTS `project_tasks`;

CREATE TABLE `project_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `assigned_to` bigint DEFAULT NULL,
  `status` enum('todo','in_progress','review','completed','blocked') COLLATE utf8mb4_unicode_ci DEFAULT 'todo',
  `priority` enum('low','medium','high','critical') COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `start_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `estimated_hours` decimal(10,2) DEFAULT NULL,
  `actual_hours` decimal(10,2) DEFAULT NULL,
  `parent_task_id` bigint DEFAULT NULL COMMENT 'For subtasks',
  `order_index` int DEFAULT '0',
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `parent_task_id` (`parent_task_id`),
  KEY `created_by` (`created_by`),
  KEY `idx_project` (`project_id`),
  KEY `idx_assigned` (`assigned_to`),
  KEY `idx_status` (`status`),
  CONSTRAINT `project_tasks_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_tasks_ibfk_2` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `project_tasks_ibfk_3` FOREIGN KEY (`parent_task_id`) REFERENCES `project_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_tasks_ibfk_4` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_team_members
-- Rows: 0, Size: 0.09 MB
-- Foreign Keys: 5
--   project_id -> projects(id)
--   department_id -> departments(id)
--   team_id -> teams(id)
--   user_id -> users(id)
--   assigned_by -> users(id)

DROP TABLE IF EXISTS `project_team_members`;

CREATE TABLE `project_team_members` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `department_id` bigint NOT NULL,
  `team_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `role` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'member',
  `assigned_by` bigint DEFAULT NULL,
  `assigned_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_project_member` (`project_id`,`user_id`),
  KEY `department_id` (`department_id`),
  KEY `team_id` (`team_id`),
  KEY `user_id` (`user_id`),
  KEY `assigned_by` (`assigned_by`),
  CONSTRAINT `project_team_members_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_team_members_ibfk_2` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_team_members_ibfk_3` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_team_members_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_team_members_ibfk_5` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: project_warnings
-- Rows: 6, Size: 0.14 MB
-- Foreign Keys: 6
--   project_id -> projects(id)
--   department_task_id -> project_department_tasks(id)
--   member_task_id -> project_member_tasks(id)
--   warned_user_id -> users(id)
--   issued_by -> users(id)
--   acknowledged_by -> users(id)

DROP TABLE IF EXISTS `project_warnings`;

CREATE TABLE `project_warnings` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `department_task_id` bigint DEFAULT NULL,
  `member_task_id` bigint DEFAULT NULL,
  `warned_user_id` bigint NOT NULL,
  `issued_by` bigint NOT NULL COMMENT 'Admin/Manager who issued warning',
  `warning_type` enum('late_submission','poor_quality','missed_deadline','incomplete_work','other') COLLATE utf8mb4_unicode_ci NOT NULL,
  `severity` enum('low','medium','high','critical') COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `reason` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `penalty_amount` decimal(10,2) DEFAULT NULL COMMENT 'Financial penalty if applicable',
  `acknowledged_at` datetime DEFAULT NULL,
  `acknowledged_by` bigint DEFAULT NULL,
  `issued_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `department_task_id` (`department_task_id`),
  KEY `member_task_id` (`member_task_id`),
  KEY `issued_by` (`issued_by`),
  KEY `acknowledged_by` (`acknowledged_by`),
  KEY `idx_project` (`project_id`),
  KEY `idx_warned_user` (`warned_user_id`),
  KEY `idx_severity` (`severity`),
  KEY `idx_issued_at` (`issued_at`),
  CONSTRAINT `project_warnings_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_warnings_ibfk_2` FOREIGN KEY (`department_task_id`) REFERENCES `project_department_tasks` (`id`) ON DELETE SET NULL,
  CONSTRAINT `project_warnings_ibfk_3` FOREIGN KEY (`member_task_id`) REFERENCES `project_member_tasks` (`id`) ON DELETE SET NULL,
  CONSTRAINT `project_warnings_ibfk_4` FOREIGN KEY (`warned_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_warnings_ibfk_5` FOREIGN KEY (`issued_by`) REFERENCES `users` (`id`),
  CONSTRAINT `project_warnings_ibfk_6` FOREIGN KEY (`acknowledged_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: projects
-- Rows: 28, Size: 0.06 MB
-- Foreign Keys: 2
--   department_id -> departments(id)
--   manager_id -> users(id)

DROP TABLE IF EXISTS `projects`;

CREATE TABLE `projects` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `department_id` bigint DEFAULT NULL,
  `team_id` bigint DEFAULT NULL,
  `manager_id` bigint DEFAULT NULL,
  `status` enum('planning','in_progress','completed','on_hold','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'planning',
  `priority` enum('low','medium','high','critical') COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `progress` int DEFAULT '0' COMMENT 'Progress percentage 0-100',
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `budget` decimal(15,2) DEFAULT NULL,
  `attachments` json DEFAULT NULL COMMENT 'Project attachments/documents',
  `metadata` json DEFAULT NULL COMMENT 'Additional project metadata',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `manager_id` (`manager_id`),
  KEY `idx_status` (`status`),
  KEY `idx_department` (`department_id`),
  CONSTRAINT `projects_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `projects_ibfk_2` FOREIGN KEY (`manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: reaction_types
-- Rows: 5, Size: 0.03 MB

DROP TABLE IF EXISTS `reaction_types`;

CREATE TABLE `reaction_types` (
  `id` tinyint NOT NULL AUTO_INCREMENT,
  `code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `emoji` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: reactions
-- Rows: 3, Size: 0.05 MB
-- Foreign Keys: 1
--   user_id -> users(id)

DROP TABLE IF EXISTS `reactions`;

CREATE TABLE `reactions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `target_type` enum('post','comment') COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_id` bigint NOT NULL,
  `reaction_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'like',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_target` (`user_id`,`target_type`,`target_id`),
  KEY `idx_target` (`target_type`,`target_id`),
  CONSTRAINT `reactions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: reports
-- Rows: 0, Size: 0.11 MB
-- Foreign Keys: 3
--   reporter_id -> users(id)
--   handled_by -> users(id)
--   department_id -> departments(id)

DROP TABLE IF EXISTS `reports`;

CREATE TABLE `reports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reporter_id` bigint NOT NULL,
  `target_type` enum('post','comment','user','message') COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_id` bigint NOT NULL,
  `reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `details` text COLLATE utf8mb4_unicode_ci,
  `status` enum('open','in_progress','resolved','dismissed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `handled_by` bigint DEFAULT NULL,
  `department_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved_at` datetime DEFAULT NULL,
  `resolution_note` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `reporter_id` (`reporter_id`),
  KEY `handled_by` (`handled_by`),
  KEY `department_id` (`department_id`),
  KEY `idx_status` (`status`),
  KEY `idx_target` (`target_type`,`target_id`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `reports_ibfk_1` FOREIGN KEY (`reporter_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reports_ibfk_2` FOREIGN KEY (`handled_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `reports_ibfk_3` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: role_permissions
-- Rows: 111, Size: 0.03 MB
-- Foreign Keys: 2
--   role_id -> roles(id)
--   permission_id -> permissions(id)

DROP TABLE IF EXISTS `role_permissions`;

CREATE TABLE `role_permissions` (
  `role_id` int NOT NULL,
  `permission_id` int NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: roles
-- Rows: 7, Size: 0.05 MB

DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: saved_posts
-- Rows: 0, Size: 0.06 MB
-- Foreign Keys: 2
--   user_id -> users(id)
--   post_id -> posts(id)

DROP TABLE IF EXISTS `saved_posts`;

CREATE TABLE `saved_posts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `post_id` bigint NOT NULL,
  `saved_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `collection_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_post` (`user_id`,`post_id`),
  KEY `post_id` (`post_id`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `saved_posts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `saved_posts_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: system_settings
-- Rows: 7, Size: 0.03 MB

DROP TABLE IF EXISTS `system_settings`;

CREATE TABLE `system_settings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `setting_value` text COLLATE utf8mb4_unicode_ci,
  `data_type` enum('string','number','boolean','json') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'string',
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: tasks
-- Rows: 45, Size: 0.08 MB
-- Foreign Keys: 3
--   project_id -> projects(id)
--   assigned_to -> users(id)
--   created_by -> users(id)

DROP TABLE IF EXISTS `tasks`;

CREATE TABLE `tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `project_id` bigint DEFAULT NULL,
  `assigned_to` bigint DEFAULT NULL,
  `created_by` bigint NOT NULL,
  `priority` enum('low','medium','high','urgent') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'medium',
  `status` enum('pending','in_progress','completed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `due_date` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_status` (`status`),
  KEY `idx_assigned` (`assigned_to`),
  KEY `idx_project` (`project_id`),
  CONSTRAINT `tasks_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tasks_ibfk_2` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tasks_ibfk_3` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: team_members
-- Rows: 3, Size: 0.03 MB
-- Foreign Keys: 2
--   team_id -> teams(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `team_members`;

CREATE TABLE `team_members` (
  `team_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `role_in_team` enum('member','owner','manager') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'member',
  `joined_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`team_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `team_members_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON DELETE CASCADE,
  CONSTRAINT `team_members_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: teams
-- Rows: 25, Size: 0.06 MB
-- Foreign Keys: 2
--   department_id -> departments(id)
--   created_by -> users(id)

DROP TABLE IF EXISTS `teams`;

CREATE TABLE `teams` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `department_id` bigint DEFAULT NULL,
  `is_private` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `description` text COLLATE utf8mb4_unicode_ci,
  `avatar_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_dept` (`department_id`),
  KEY `idx_is_active` (`is_active`),
  CONSTRAINT `teams_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `teams_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: typing_indicators
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 2
--   conversation_id -> conversations(id)
--   user_id -> users(id)

DROP TABLE IF EXISTS `typing_indicators`;

CREATE TABLE `typing_indicators` (
  `conversation_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` datetime NOT NULL,
  PRIMARY KEY (`conversation_id`,`user_id`),
  KEY `user_id` (`user_id`),
  KEY `idx_expires` (`expires_at`),
  CONSTRAINT `typing_indicators_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `typing_indicators_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: user_activity_stats
-- Rows: 0, Size: 0.02 MB
-- Foreign Keys: 1
--   user_id -> users(id)

DROP TABLE IF EXISTS `user_activity_stats`;

CREATE TABLE `user_activity_stats` (
  `user_id` bigint NOT NULL,
  `posts_count` int NOT NULL DEFAULT '0',
  `comments_count` int NOT NULL DEFAULT '0',
  `reactions_given` int NOT NULL DEFAULT '0',
  `reactions_received` int NOT NULL DEFAULT '0',
  `shares_count` int NOT NULL DEFAULT '0',
  `last_post_at` datetime DEFAULT NULL,
  `last_comment_at` datetime DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `user_activity_stats_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: user_connections
-- Rows: 0, Size: 0.06 MB
-- Foreign Keys: 2
--   user_id -> users(id)
--   connected_user_id -> users(id)

DROP TABLE IF EXISTS `user_connections`;

CREATE TABLE `user_connections` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `connected_user_id` bigint NOT NULL,
  `status` enum('pending','accepted','blocked') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `requested_by` bigint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_connection` (`user_id`,`connected_user_id`),
  KEY `connected_user_id` (`connected_user_id`),
  KEY `idx_user_status` (`user_id`,`status`),
  CONSTRAINT `user_connections_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_connections_ibfk_2` FOREIGN KEY (`connected_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: user_roles
-- Rows: 118, Size: 0.08 MB
-- Foreign Keys: 3
--   user_id -> users(id)
--   role_id -> roles(id)
--   department_id -> departments(id)

DROP TABLE IF EXISTS `user_roles`;

CREATE TABLE `user_roles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `role_id` int NOT NULL,
  `department_id` bigint DEFAULT NULL,
  `assigned_by` bigint DEFAULT NULL,
  `assigned_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_role_dept` (`user_id`,`role_id`,`department_id`),
  KEY `role_id` (`role_id`),
  KEY `department_id` (`department_id`),
  KEY `idx_user_dept` (`user_id`,`department_id`),
  CONSTRAINT `user_roles_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_roles_ibfk_2` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_roles_ibfk_3` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=143 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: user_sessions
-- Rows: 0, Size: 0.05 MB
-- Foreign Keys: 1
--   user_id -> users(id)

DROP TABLE IF EXISTS `user_sessions`;

CREATE TABLE `user_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `session_token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ended_at` datetime DEFAULT NULL,
  `last_activity` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_token` (`session_token`),
  CONSTRAINT `user_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: users
-- Rows: 113, Size: 0.14 MB

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` datetime DEFAULT NULL,
  `status` enum('active','suspended','resigned','disabled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `is_system_admin` tinyint(1) NOT NULL DEFAULT '0',
  `profile_id` bigint DEFAULT NULL,
  `settings` json DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` datetime DEFAULT NULL,
  `is_online` tinyint(1) NOT NULL DEFAULT '0',
  `last_seen` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_email` (`email`),
  KEY `idx_username` (`username`),
  KEY `idx_status` (`status`),
  KEY `idx_is_online` (`is_online`)
) ENGINE=InnoDB AUTO_INCREMENT=152 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: v_active_users
-- Rows: 0, Size: 0 MB

DROP TABLE IF EXISTS `v_active_users`;

undefined;

-- Table: v_posts_with_author
-- Rows: 0, Size: 0 MB

DROP TABLE IF EXISTS `v_posts_with_author`;

undefined;


-- ================================================================
-- VIEWS
-- ================================================================

DROP VIEW IF EXISTS `v_active_users`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_active_users` AS select `u`.`id` AS `id`,`u`.`username` AS `username`,`u`.`email` AS `email`,`u`.`status` AS `status`,`u`.`is_online` AS `is_online`,`u`.`last_seen` AS `last_seen`,`p`.`full_name` AS `full_name`,`p`.`avatar_url` AS `avatar_url`,`p`.`bio` AS `bio`,`er`.`position` AS `position`,`d`.`name` AS `department_name` from (((`users` `u` left join `profiles` `p` on((`u`.`id` = `p`.`user_id`))) left join `employee_records` `er` on(((`u`.`id` = `er`.`user_id`) and (`er`.`status` = 'active')))) left join `departments` `d` on((`er`.`department_id` = `d`.`id`))) where ((`u`.`status` = 'active') and (`u`.`is_deleted` = false));

DROP VIEW IF EXISTS `v_posts_with_author`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_posts_with_author` AS select `p`.`id` AS `id`,`p`.`author_id` AS `author_id`,`p`.`department_id` AS `department_id`,`p`.`team_id` AS `team_id`,`p`.`category_id` AS `category_id`,`p`.`title` AS `title`,`p`.`content` AS `content`,`p`.`content_html` AS `content_html`,`p`.`visibility` AS `visibility`,`p`.`allowed_group_id` AS `allowed_group_id`,`p`.`created_at` AS `created_at`,`p`.`updated_at` AS `updated_at`,`p`.`edited` AS `edited`,`p`.`is_deleted` AS `is_deleted`,`p`.`deleted_at` AS `deleted_at`,`p`.`deleted_by` AS `deleted_by`,`p`.`reply_count` AS `reply_count`,`p`.`reaction_count` AS `reaction_count`,`p`.`view_count` AS `view_count`,`p`.`share_count` AS `share_count`,`p`.`pinned` AS `pinned`,`p`.`pinned_until` AS `pinned_until`,`p`.`pinned_by` AS `pinned_by`,`u`.`username` AS `author_username`,`pr`.`full_name` AS `author_name`,`pr`.`avatar_url` AS `author_avatar`,`d`.`name` AS `department_name`,`pc`.`name` AS `category_name` from ((((`posts` `p` join `users` `u` on((`p`.`author_id` = `u`.`id`))) left join `profiles` `pr` on((`u`.`id` = `pr`.`user_id`))) left join `departments` `d` on((`p`.`department_id` = `d`.`id`))) left join `post_categories` `pc` on((`p`.`category_id` = `pc`.`id`))) where (`p`.`is_deleted` = false);


-- ================================================================
-- TRIGGERS
-- ================================================================

DELIMITER $$

DROP TRIGGER IF EXISTS `trg_comment_reaction_count_insert`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_comment_reaction_count_insert` AFTER INSERT ON `comment_reactions` FOR EACH ROW BEGIN
  UPDATE comments SET reaction_count = reaction_count + 1 WHERE id = NEW.comment_id;
END$$

DROP TRIGGER IF EXISTS `trg_comment_reaction_count_delete`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_comment_reaction_count_delete` AFTER DELETE ON `comment_reactions` FOR EACH ROW BEGIN
  UPDATE comments SET reaction_count = reaction_count - 1 WHERE id = OLD.comment_id;
END$$

DROP TRIGGER IF EXISTS `trg_post_reply_count_insert`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_post_reply_count_insert` AFTER INSERT ON `comments` FOR EACH ROW BEGIN
  UPDATE posts SET reply_count = reply_count + 1 WHERE id = NEW.post_id;
END$$

DROP TRIGGER IF EXISTS `trg_post_reply_count_delete`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_post_reply_count_delete` AFTER DELETE ON `comments` FOR EACH ROW BEGIN
  UPDATE posts SET reply_count = reply_count - 1 WHERE id = OLD.post_id;
END$$

DROP TRIGGER IF EXISTS `trg_conversation_last_message`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_conversation_last_message` AFTER INSERT ON `messages` FOR EACH ROW BEGIN
  UPDATE conversations SET last_message_at = NEW.created_at WHERE id = NEW.conversation_id;
END$$

DROP TRIGGER IF EXISTS `trg_hashtag_usage_insert`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_hashtag_usage_insert` AFTER INSERT ON `post_hashtags` FOR EACH ROW BEGIN
  UPDATE hashtags SET usage_count = usage_count + 1 WHERE id = NEW.hashtag_id;
END$$

DROP TRIGGER IF EXISTS `trg_hashtag_usage_delete`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_hashtag_usage_delete` AFTER DELETE ON `post_hashtags` FOR EACH ROW BEGIN
  UPDATE hashtags SET usage_count = usage_count - 1 WHERE id = OLD.hashtag_id;
END$$

DROP TRIGGER IF EXISTS `trg_post_reaction_count_insert`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_post_reaction_count_insert` AFTER INSERT ON `post_reactions` FOR EACH ROW BEGIN
  UPDATE posts SET reaction_count = reaction_count + 1 WHERE id = NEW.post_id;
END$$

DROP TRIGGER IF EXISTS `trg_post_reaction_count_delete`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_post_reaction_count_delete` AFTER DELETE ON `post_reactions` FOR EACH ROW BEGIN
  UPDATE posts SET reaction_count = reaction_count - 1 WHERE id = OLD.post_id;
END$$

DROP TRIGGER IF EXISTS `trg_post_share_count_insert`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_post_share_count_insert` AFTER INSERT ON `post_shares` FOR EACH ROW BEGIN
  UPDATE posts SET share_count = share_count + 1 WHERE id = NEW.post_id;
END$$

DROP TRIGGER IF EXISTS `trg_post_share_count_delete`$$

CREATE DEFINER=`root`@`localhost` TRIGGER `trg_post_share_count_delete` AFTER DELETE ON `post_shares` FOR EACH ROW BEGIN
  UPDATE posts SET share_count = share_count - 1 WHERE id = OLD.post_id;
END$$

DELIMITER ;


-- ================================================================
-- STORED PROCEDURES
-- ================================================================

DELIMITER $$

DROP PROCEDURE IF EXISTS `sp_create_notification`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_create_notification`(
  IN p_user_id BIGINT,
  IN p_actor_id BIGINT,
  IN p_type VARCHAR(150),
  IN p_reference_type VARCHAR(50),
  IN p_reference_id BIGINT,
  IN p_payload JSON
)
BEGIN
  
  DECLARE v_enabled BOOLEAN;
  
  SELECT enabled INTO v_enabled
  FROM notification_preferences
  WHERE user_id = p_user_id AND notification_type = p_type
  LIMIT 1;
  
  IF v_enabled IS NULL THEN
    SET v_enabled = TRUE; 
  END IF;
  
  IF v_enabled = TRUE THEN
    INSERT INTO notifications (user_id, actor_id, type, reference_type, reference_id, payload)
    VALUES (p_user_id, p_actor_id, p_type, p_reference_type, p_reference_id, p_payload);
  END IF;
END$$

DROP PROCEDURE IF EXISTS `sp_get_user_feed`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_get_user_feed`(
  IN p_user_id BIGINT,
  IN p_limit INT,
  IN p_offset INT
)
BEGIN
  
  DECLARE v_dept_id BIGINT;
  SELECT department_id INTO v_dept_id 
  FROM employee_records 
  WHERE user_id = p_user_id AND status = 'active' 
  LIMIT 1;
  
  
  SELECT DISTINCT p.*
  FROM posts p
  WHERE p.is_deleted = FALSE
    AND (
      p.visibility = 'company'
      OR (p.visibility = 'department' AND p.department_id = v_dept_id)
      OR p.author_id = p_user_id
    )
  ORDER BY p.created_at DESC
  LIMIT p_limit OFFSET p_offset;
END$$

DELIMITER ;


SET FOREIGN_KEY_CHECKS = 1;

-- ================================================================
-- END OF EXPORT
-- ================================================================